name: test
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
